FROM nginx:1.27-alpine

LABEL maintainer="Harun Ozturko"
LABEL description="Nginx 1.27 — Reverse Proxy (Symfony + Angular)"

# Varsayılan config'i kaldır
RUN rm -f /etc/nginx/conf.d/default.conf

EXPOSE 80
